---
title: "Boddy brains"
author: "Brian Schilder"
date: "February 26, 2015"
output: html_document
---
```{r}
library(dplyr)
library(ggplot2)

boddy <- read.table(file="/Users/schilder/Desktop/Rdata/BODDY.csv", sep=",", header=TRUE)
str(boddy)
brainclimate <- read.table(file="/Users/schilder/Desktop/Rdata/brainclimatedata.txt", header=TRUE, sep="\t")
str(brainclimate)

##Species counts within Orders
# as.data.frame(table(boddy$Order))
# as.data.frame(table(brainclimate$Order))
```
#5MY Interval
```{r}
Oxy_Int5m.Last5 <- ggplot(data=brainclimate) + xlim(-5, 0) + ylim(-10, 10) +
  geom_line(aes(y=X5Mya_M_oxy, x=Actual.MYA, color="blue")) + 
  geom_line(aes(y=X5Mya_SD_oxy , x=Actual.MYA, color="red")) + 
  geom_line(aes(y=X5Mya_slope_oxy , x=Actual.MYA, color="green")) +
  annotate("text", x= -4, y= 10, label="SD", color="red") + 
  annotate("text", x= -4, y= 8, label="Mean", color="blue") +
  annotate("text", x= -4, y= 6, label="Slope", color="green") +
  labs(y="d18O", title="5My Interval, Last 5My") +
  theme(legend.position = "none")
Oxy_Int5m.Last5

Oxy_Int5m.Last65 <- ggplot(data=brainclimate) + 
  geom_line(aes(y=X5Mya_M_oxy, x=Actual.MYA, color="blue")) + 
  geom_line(aes(y=X5Mya_SD_oxy , x=Actual.MYA, color="red")) + 
  geom_line(aes(y=X5Mya_slope_oxy , x=Actual.MYA, color="green")) +
  annotate("text", x= -4, y= 2, label="SD", color="red") + 
  annotate("text", x= -4, y= 1.8, label="Mean", color="blue") +
  annotate("text", x= -4, y= 1.6, label="Slope", color="green") +
  labs(y="d18O", title="5My Interval, Last 65My") +
  theme(legend.position = "none")
Oxy_Int5m.Last65
```
#1MY Interval
```{r}
Oxy_Int1m.Last5 <- ggplot(data=brainclimate) + xlim(-5, 0) + ylim(-10, 10) +
  geom_line(aes(y=X1Mya_M_oxy, x=Actual.MYA, color="blue")) + 
  geom_line(aes(y=X1Mya_SD_oxy , x=Actual.MYA, color="red")) + 
  geom_line(aes(y=X1Mya_slope_oxy , x=Actual.MYA, color="green")) +
  annotate("text", x= -4, y= 10, label="SD", color="red") + 
  annotate("text", x= -4, y= 8, label="Mean", color="blue") +
  annotate("text", x= -4, y= 6, label="Slope", color="green") +
  labs(y="d18O", title="1My Interval, Last 5My") +
  theme(legend.position = "none")
Oxy_Int1m.Last5

Oxy_Int1m.Last65 <- ggplot(data=brainclimate) + 
  geom_line(aes(y=X1Mya_M_oxy, x=Actual.MYA, color="blue")) + 
  geom_line(aes(y=X1Mya_SD_oxy , x=Actual.MYA, color="red")) + 
  geom_line(aes(y=X1Mya_slope_oxy , x=Actual.MYA, color="green")) +
  annotate("text", x= -4, y= 2, label="SD", color="red") + 
  annotate("text", x= -4, y= 1.8, label="Mean", color="blue") +
  annotate("text", x= -4, y= 1.6, label="Slope", color="green") +
  labs(y="d18O", title="1My Interval, Last 65My") +
  theme(legend.position = "none")
Oxy_Int1m.Last65
```
#400K Interval
```{r}
Oxy_Int400k.Last5 <- ggplot(data=brainclimate) + xlim(-5, 0) + ylim(-10, 10) +
  geom_line(aes(y=X400k_M_oxy, x=Actual.MYA, color="blue")) + 
  geom_line(aes(y=X400k_SD_oxy , x=Actual.MYA, color="red")) + 
  geom_line(aes(y=X400k_slope_oxy , x=Actual.MYA, color="green")) +
  annotate("text", x= -4, y= 10, label="SD", color="red") + 
  annotate("text", x= -4, y= 8, label="Mean", color="blue") +
  annotate("text", x= -4, y= 6, label="Slope", color="green") +
  labs(y="d18O", title="400k Interval, Last 5My") +
  theme(legend.position = "none")
Oxy_Int400k.Last5

Oxy_Int400k.Last65 <- ggplot(data=brainclimate) + 
  geom_line(aes(y=X400k_M_oxy, x=Actual.MYA, color="blue")) + 
  geom_line(aes(y=X400k_SD_oxy , x=Actual.MYA, color="red")) + 
  geom_line(aes(y=X400k_slope_oxy , x=Actual.MYA, color="green")) +
  annotate("text", x= -4, y= 2, label="SD", color="red") + 
  annotate("text", x= -4, y= 1.8, label="Mean", color="blue") +
  annotate("text", x= -4, y= 1.6, label="Slope", color="green") +
 labs(y="d18O", title="400k Interval, Last 65My") +
  theme(legend.position = "none")
Oxy_Int400k.Last65
```
#200K Interval
```{r}
Oxy_Int200k.Last5 <- ggplot(data=brainclimate) + xlim(-5, 0) + ylim(-10, 10) +
  geom_line(aes(y=X200K_M_oxy, x=Actual.MYA, color="blue")) + 
  geom_line(aes(y=X200K_SD_oxy , x=Actual.MYA, color="red")) + 
  geom_line(aes(y=X200K_slope_oxy , x=Actual.MYA, color="green")) +
  annotate("text", x= -4, y= 10, label="SD", color="red") + 
  annotate("text", x= -4, y= 8, label="Mean", color="blue") +
  annotate("text", x= -4, y= 6, label="Slope", color="green") +
  labs(y="d18O", title="200k Interval, Last 5My") +
  theme(legend.position = "none")
Oxy_Int200k.Last5

Oxy_Int200k.Last65 <- ggplot(data=brainclimate) + 
  geom_line(aes(y=X200K_M_oxy, x=Actual.MYA, color="blue")) + 
  geom_line(aes(y=X200K_SD_oxy , x=Actual.MYA, color="red")) + 
  geom_line(aes(y=X200K_slope_oxy , x=Actual.MYA, color="green")) +
  annotate("text", x= -4, y= 2, label="SD", color="red") + 
  annotate("text", x= -4, y= 1.8, label="Mean", color="blue") +
  annotate("text", x= -4, y= 1.6, label="Slope", color="green") +
  labs(y="d18O", title="200k Interval, Last 65My") +
  theme(legend.position = "none")
Oxy_Int200k.Last65
```
#100K Interval
```{r}
Oxy_Int100k.Last5 <- ggplot(data=brainclimate) + xlim(-5, 0) + ylim(-10, 10) +
  geom_line(aes(y=X100k_M_oxy, x=Actual.MYA, color="blue")) + 
  geom_line(aes(y=X100k_SD_oxy , x=Actual.MYA, color="red")) + 
  geom_line(aes(y=X100k_slope_oxy , x=Actual.MYA, color="green")) +
  annotate("text", x= -4, y= 10, label="SD", color="red") + 
  annotate("text", x= -4, y= 8, label="Mean", color="blue") +
  annotate("text", x= -4, y= 6, label="Slope", color="green") +
  labs(y="d18O", title="100k Interval, Last 5My") +
  theme(legend.position = "none")
Oxy_Int100k.Last5

Oxy_Int100k.Last65 <- ggplot(data=brainclimate) + 
  geom_line(aes(y=X100k_M_oxy, x=Actual.MYA, color="blue")) + 
  geom_line(aes(y=X100k_SD_oxy , x=Actual.MYA, color="red")) + 
  geom_line(aes(y=X100k_slope_oxy , x=Actual.MYA, color="green")) +
  annotate("text", x= -4, y= 2, label="SD", color="red") + 
  annotate("text", x= -4, y= 1.8, label="Mean", color="blue") +
  annotate("text", x= -4, y= 1.6, label="Slope", color="green") +
  labs(y="d18O", title="100k Interval, Last 65My") +
  theme(legend.position = "none")
Oxy_Int100k.Last65
```
#40K Interval
```{r}
Oxy_Int40k.Last5 <- ggplot(data=brainclimate) + xlim(-5, 0) + ylim(-10, 10) +
  geom_line(aes(y=X40k_M_oxy, x=Actual.MYA, color="blue")) + 
  geom_line(aes(y=X40k_SD_oxy , x=Actual.MYA, color="red")) + 
  geom_line(aes(y=X40k_slope_oxy , x=Actual.MYA, color="green")) +
  annotate("text", x= -4, y= 10, label="SD", color="red") + 
  annotate("text", x= -4, y= 8, label="Mean", color="blue") +
  annotate("text", x= -4, y= 6, label="Slope", color="green") +
  labs(y="d18O", title="40k Interval, Last 5My") +
  theme(legend.position = "none")
Oxy_Int40k.Last5

Oxy_Int40k.Last65 <- ggplot(data=brainclimate) + 
  geom_line(aes(y=X40k_M_oxy, x=Actual.MYA, color="blue")) + 
  geom_line(aes(y=X40k_SD_oxy , x=Actual.MYA, color="red")) + 
  geom_line(aes(y=X40k_slope_oxy , x=Actual.MYA, color="green")) +
  annotate("text", x= -4, y= 2, label="SD", color="red") + 
  annotate("text", x= -4, y= 1.8, label="Mean", color="blue") +
  annotate("text", x= -4, y= 1.6, label="Slope", color="green") +
  labs(y="d18O", title="40k Interval, Last 5My") +
  theme(legend.position = "none")
Oxy_Int40k.Last65
```
#Multiplot With All Intervals
```{r echo=FALSE}
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  require(grid)
  plots <- c(list(...), plotlist)
  numPlots = length(plots)
  if (is.null(layout)) {
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }
 if (numPlots==1) {
    print(plots[[1]])
  } else {
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    for (i in 1:numPlots) {
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

```{r}

Uber.plot <- multiplot(Oxy_Int5m.Last5, 
          Oxy_Int1m.Last5, 
          Oxy_Int400k.Last5, 
          Oxy_Int200k.Last5, 
          Oxy_Int100k.Last5, 
          Oxy_Int40k.Last5, cols=3)

pdf(file=Uber.Plot, title="All_Intervals.pdf", width=20, height=200)
Uber.plot
dev.off()


